language: node_js
node_js:
 — “8.9.4”
branches:
 only:
 — master
before_script:
 — npm install -g ionic cordova jest
script:
 — ionic cordova build browser — prod
deploy:
 provider: pages
 skip-cleanup: true
 github-token: $GITHUB_TOKEN 
 keep-history: true
 on:
   branch: master
 local_dir: www